/**
 * This script uses the `icons.json` generated by the base SDS repo's script (https://github.com/figma/sds/tree/main/scripts/icons)
 */
import { convertToKebabCase } from '../utils';
import data from './icons.json';
import fs from 'fs/promises';

const OutputFile = 'src/figma/icons/sds-icons.figma.ts';

const createIconsFigmaFile = async () => {
  const nodeIdRegex = new RegExp(/node-id=(\d+:\d+)/);

  const output = `import figma, { html } from '@figma/code-connect/html';

// generated via \`sds-web-components/scripts/generate-icon-files/create-icons-figma-file/\`

${data
  .map(([pascalName, _component, figmaConnect]) => {
    if (!figmaConnect || !pascalName) {
      return '';
    }
    const match = nodeIdRegex.exec(figmaConnect);
    if (!match) {
      return;
    }
    const nodeId = match[1];

    const name = convertToKebabCase(pascalName);

    return `figma.connect('<FIGMA_ICONS_BASE>?node-id=${nodeId}', {
\tprops: { size: figma.enum('Size', { '20': '20', '24': '24', '32': '32', '40': '40', '48': '48' }) },
\texample: ({ size }) => html\`<sds-${name} size=\${size}></sds-${name}>\`,
});`;
  })
  .join('\n')}
  `;

  await fs.writeFile(OutputFile, output, { encoding: 'utf-8' });
};

createIconsFigmaFile();
