/**
 * This script uses the `icons.json` generated by the base SDS repo's script (https://github.com/figma/sds/tree/main/scripts/icons)
 */
import data from './icons.json';
import fs from 'fs/promises';
import { configureVue } from './configure-vue';
import { configureWeb } from './configure-web';
import { configureReact } from './configure-react';

const BASE_ICON_FOLDER = 'src/code-connect/icons';

const OUTPUTS = {
  web: {
    dataParser: configureWeb,
  },
  angular: {
    dataParser: configureWeb,
  },
  vue: {
    dataParser: configureVue,
  },
  react: {
    dataParser: configureReact,
  },
};

const createIconsFigmaFile = async () => {
  const outputs = Object.entries(OUTPUTS);
  for (let i = 0; i < outputs.length; i += 1) {
    const [name, config] = outputs[i];

    const outputData = config.dataParser(data);
    const outputFolder = `${BASE_ICON_FOLDER}/${name}/`;
    const outputFilePath = `${outputFolder}/sds-icons.figma.ts${name === 'react' ? 'x' : ''}`;

    await fs.mkdir(outputFolder, { recursive: true });
    await fs.writeFile(outputFilePath, outputData, { encoding: 'utf-8' });
  }
};

createIconsFigmaFile();
