/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Size, Type } from "./ui/primitives/SdsButton/SdsButtonBase";
import { DefaultVariant } from "./ui/primitives/SdsButton/SdsButton";
import { Size as Size1, Type as Type1, Variant } from "./ui/primitives/SdsButton/SdsButtonBase";
import { DangerVariant } from "./ui/primitives/SdsButton/SdsButtonDanger";
export { Size, Type } from "./ui/primitives/SdsButton/SdsButtonBase";
export { DefaultVariant } from "./ui/primitives/SdsButton/SdsButton";
export { Size as Size1, Type as Type1, Variant } from "./ui/primitives/SdsButton/SdsButtonBase";
export { DangerVariant } from "./ui/primitives/SdsButton/SdsButtonDanger";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SdsButton {
        /**
          * The button size
         */
        "size"?: Size;
        /**
          * The button type
         */
        "type"?: Type;
        /**
          * The button default variant
         */
        "variant"?: DefaultVariant;
    }
    interface SdsButtonBase {
        /**
          * The button size
         */
        "size"?: Size1;
        /**
          * The button type
         */
        "type"?: Type1;
        /**
          * The button variant
         */
        "variant"?: Variant;
    }
    interface SdsButtonDanger {
        /**
          * The button size
         */
        "size"?: Size;
        /**
          * The button type
         */
        "type"?: Type;
        /**
          * The button danger variant
         */
        "variant"?: DangerVariant;
    }
    interface SdsButtonGroup {
        "align"?: 'start' | 'end' | 'center' | 'justify' | 'stack';
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSdsButtonElement extends Components.SdsButton, HTMLStencilElement {
    }
    var HTMLSdsButtonElement: {
        prototype: HTMLSdsButtonElement;
        new (): HTMLSdsButtonElement;
    };
    interface HTMLSdsButtonBaseElement extends Components.SdsButtonBase, HTMLStencilElement {
    }
    var HTMLSdsButtonBaseElement: {
        prototype: HTMLSdsButtonBaseElement;
        new (): HTMLSdsButtonBaseElement;
    };
    interface HTMLSdsButtonDangerElement extends Components.SdsButtonDanger, HTMLStencilElement {
    }
    var HTMLSdsButtonDangerElement: {
        prototype: HTMLSdsButtonDangerElement;
        new (): HTMLSdsButtonDangerElement;
    };
    interface HTMLSdsButtonGroupElement extends Components.SdsButtonGroup, HTMLStencilElement {
    }
    var HTMLSdsButtonGroupElement: {
        prototype: HTMLSdsButtonGroupElement;
        new (): HTMLSdsButtonGroupElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sds-button": HTMLSdsButtonElement;
        "sds-button-base": HTMLSdsButtonBaseElement;
        "sds-button-danger": HTMLSdsButtonDangerElement;
        "sds-button-group": HTMLSdsButtonGroupElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SdsButton {
        /**
          * The button size
         */
        "size"?: Size;
        /**
          * The button type
         */
        "type"?: Type;
        /**
          * The button default variant
         */
        "variant"?: DefaultVariant;
    }
    interface SdsButtonBase {
        /**
          * The button size
         */
        "size"?: Size1;
        /**
          * The button type
         */
        "type"?: Type1;
        /**
          * The button variant
         */
        "variant"?: Variant;
    }
    interface SdsButtonDanger {
        /**
          * The button size
         */
        "size"?: Size;
        /**
          * The button type
         */
        "type"?: Type;
        /**
          * The button danger variant
         */
        "variant"?: DangerVariant;
    }
    interface SdsButtonGroup {
        "align"?: 'start' | 'end' | 'center' | 'justify' | 'stack';
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sds-button": SdsButton;
        "sds-button-base": SdsButtonBase;
        "sds-button-danger": SdsButtonDanger;
        "sds-button-group": SdsButtonGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sds-button": LocalJSX.SdsButton & JSXBase.HTMLAttributes<HTMLSdsButtonElement>;
            "sds-button-base": LocalJSX.SdsButtonBase & JSXBase.HTMLAttributes<HTMLSdsButtonBaseElement>;
            "sds-button-danger": LocalJSX.SdsButtonDanger & JSXBase.HTMLAttributes<HTMLSdsButtonDangerElement>;
            "sds-button-group": LocalJSX.SdsButtonGroup & JSXBase.HTMLAttributes<HTMLSdsButtonGroupElement>;
        }
    }
}
